### ISSUE TITLE
Difference between this rollup plugin and rollup-plugin-less

### ISSUE THREAD

**Issue by ghost** [katrotz/rollup-plugin-less-modules#7]
I know this might not fit in the typical use case of opening an issue, but what exactly is the difference between this plugin and [this one](https://github.com/xiaofuzi/rollup-plugin-less)?  
I just want to import a less file from my svelte javascript (no bundling etc needed). Which one would you guys recommend?

**Comment by katrotz** [comment]
@GitGangGuy This is a rollup plugin that preprocesses the less styles into CSS and allows you either to output the CSS into a css file, or import the css content into javascript (eg. a use case would be styling angular components). The other plugin you have referenced supports only the output into a separate file (if I got it right from the description).

For svelte you could use less compiler directly (check the svelte documentation and the v2 API)
